import type { AssessmentTool } from "../../types";

export const grade1L2Baseline: AssessmentTool = {
  id: "g1-l2-baseline",
  type: "baseline",
  grade: 1,
  subject: "english",
  bookTrack: "l2",
  title: "Grade 1 English — Baseline (Start of Year)",
  description:
    "FLN readiness check before Unit 1 teaching. No prior English required for most items.",
  totalMarks: 16,
  recommendedMinutes: 25,
  version: "2025-26.1",
  administrationNotes: [
    "Conduct orally in groups of 8–10. Use A/B/C/D cards (folded paper) or fingers (1–4).",
    "Read each question twice. For performance items, demonstrate once.",
    "Record tallies on Assessor Copy while students respond — do not mark individual papers in Grade 1.",
    "If a child is absent for an item, leave notAssessed blank and exclude from that item's denominator.",
    "Baseline is not for grading children — it establishes class starting point for planning.",
  ],
  sections: [
    {
      id: "ol",
      title: "Oral Language & Listening",
      flnStrand: "OL",
      items: [
        {
          id: "BL-01",
          section: "Oral Language & Listening",
          flnStrand: "OL",
          lessonIds: [],
          competency: "Follow 1-step classroom instruction",
          bloomsLevel: "Apply",
          format: "subjective",
          marks: 2,
          deliveryMode: "performance",
          stem: "Touch your nose.",
          stimulusNote: "Teacher gives instruction once without gesture.",
          markingScheme: "2 marks: touches nose within 5 sec. 0 marks: no response or wrong body part.",
          correctResponse: "Student touches own nose",
          distractorNotes: "Touching head/ear counts as incorrect.",
        },
        {
          id: "BL-02",
          section: "Oral Language & Listening",
          flnStrand: "OL",
          lessonIds: [],
          competency: "Respond to greeting",
          bloomsLevel: "Remember",
          format: "subjective",
          marks: 2,
          deliveryMode: "oral-group",
          stem: "Teacher says: Good morning! How are you?",
          markingScheme: "2 marks: any appropriate reply (Fine/Good/Hello). 1 mark: non-verbal smile/nod only. 0: no response.",
          correctResponse: "Fine / I am fine / Good morning / Hello",
        },
      ],
    },
    {
      id: "voc",
      title: "Vocabulary (Picture)",
      flnStrand: "VOC",
      items: [
        {
          id: "BL-03",
          section: "Vocabulary (Picture)",
          flnStrand: "VOC",
          lessonIds: ["1.1"],
          competency: "Name body parts",
          bloomsLevel: "Remember",
          format: "mcq",
          marks: 1,
          deliveryMode: "oral-group",
          stem: "Show picture chart. Which is the EYES?",
          stimulusNote: "Chart: head, eyes, nose, mouth (4 labelled pictures).",
          options: [
            { key: "A", text: "Head" },
            { key: "B", text: "Eyes" },
            { key: "C", text: "Nose" },
            { key: "D", text: "Mouth" },
          ],
          correctOption: "B",
          markingScheme: "1 mark for B.",
        },
        {
          id: "BL-04",
          section: "Vocabulary (Picture)",
          flnStrand: "VOC",
          lessonIds: ["1.3"],
          competency: "Name household objects",
          bloomsLevel: "Remember",
          format: "mcq",
          marks: 1,
          deliveryMode: "oral-group",
          stem: "Which picture shows a CHAIR?",
          stimulusNote: "Chart: table, chair, door, fan.",
          options: [
            { key: "A", text: "Table" },
            { key: "B", text: "Chair" },
            { key: "C", text: "Door" },
            { key: "D", text: "Fan" },
          ],
          correctOption: "B",
          markingScheme: "1 mark for B.",
        },
      ],
    },
    {
      id: "dec",
      title: "Letter Awareness",
      flnStrand: "DEC",
      items: [
        {
          id: "BL-05",
          section: "Letter Awareness",
          flnStrand: "DEC",
          lessonIds: [],
          competency: "Recognise letter shapes",
          bloomsLevel: "Remember",
          format: "mcq",
          marks: 1,
          deliveryMode: "oral-group",
          stem: "Which letter is M?",
          stimulusNote: "Show card with four letters: A, M, S, T (large print).",
          options: [
            { key: "A", text: "A" },
            { key: "B", text: "M" },
            { key: "C", text: "S" },
            { key: "D", text: "T" },
          ],
          correctOption: "B",
          markingScheme: "1 mark for B.",
        },
        {
          id: "BL-06",
          section: "Letter Awareness",
          flnStrand: "DEC",
          lessonIds: [],
          competency: "Match initial sound to picture",
          bloomsLevel: "Understand",
          format: "mcq",
          marks: 1,
          deliveryMode: "oral-group",
          stem: "Which picture starts with /b/ — ball?",
          stimulusNote: "Pictures: ball, cat, sun, dog.",
          options: [
            { key: "A", text: "Ball" },
            { key: "B", text: "Cat" },
            { key: "C", text: "Sun" },
            { key: "D", text: "Dog" },
          ],
          correctOption: "A",
          markingScheme: "1 mark for A. Accept if student says 'ball' without choosing — count as A.",
        },
      ],
    },
    {
      id: "pa",
      title: "Phonological Awareness",
      flnStrand: "PA",
      items: [
        {
          id: "BL-07",
          section: "Phonological Awareness",
          flnStrand: "PA",
          lessonIds: [],
          competency: "Identify rhyming word",
          bloomsLevel: "Understand",
          format: "mcq",
          marks: 1,
          deliveryMode: "oral-group",
          stem: "Which word rhymes with CAT? — hat or dog?",
          options: [
            { key: "A", text: "Hat" },
            { key: "B", text: "Dog" },
            { key: "C", text: "Both" },
            { key: "D", text: "Neither" },
          ],
          correctOption: "A",
          markingScheme: "1 mark for A.",
        },
      ],
    },
    {
      id: "rf",
      title: "Early Reading",
      flnStrand: "RF",
      items: [
        {
          id: "BL-08",
          section: "Early Reading",
          flnStrand: "RF",
          lessonIds: [],
          competency: "Read own name or simple word",
          bloomsLevel: "Apply",
          format: "subjective",
          marks: 2,
          deliveryMode: "oral-individual",
          stem: "Show the child's name card (first name in capitals). Can the child read it?",
          markingScheme: "2 marks: reads full first name. 1 mark: reads 2+ letters correctly. 0: cannot read.",
          correctResponse: "Reads own first name",
          distractorNotes: "If name not available, use word CAT on card — same rubric.",
        },
      ],
    },
    {
      id: "rc",
      title: "Picture Comprehension",
      flnStrand: "RC",
      items: [
        {
          id: "BL-09",
          section: "Picture Comprehension",
          flnStrand: "RC",
          lessonIds: [],
          competency: "Answer who/what from picture",
          bloomsLevel: "Understand",
          format: "mcq",
          marks: 1,
          deliveryMode: "oral-group",
          stem: "Picture: girl with school bag. What is she carrying?",
          stimulusNote: "Simple line drawing: child with bag.",
          options: [
            { key: "A", text: "School bag" },
            { key: "B", text: "Ball" },
            { key: "C", text: "Book only" },
            { key: "D", text: "Umbrella" },
          ],
          correctOption: "A",
          markingScheme: "1 mark for A. Accept 'bag'.",
        },
      ],
    },
    {
      id: "wr",
      title: "Writing Readiness",
      flnStrand: "WR",
      items: [
        {
          id: "BL-10",
          section: "Writing Readiness",
          flnStrand: "WR",
          lessonIds: [],
          competency: "Copy or write a letter",
          bloomsLevel: "Apply",
          format: "subjective",
          marks: 2,
          deliveryMode: "performance",
          stem: "Write the letter A (capital) in the air or on slate.",
          markingScheme: "2 marks: recognisable A shape. 1 mark: attempt with wrong direction. 0: no attempt.",
          correctResponse: "Writes capital A",
        },
      ],
    },
    {
      id: "num",
      title: "Number Words (Cross-check)",
      flnStrand: "VOC",
      items: [
        {
          id: "BL-11",
          section: "Number Words (Cross-check)",
          flnStrand: "VOC",
          lessonIds: [],
          competency: "Count objects 1–5 in English",
          bloomsLevel: "Apply",
          format: "mcq",
          marks: 1,
          deliveryMode: "oral-group",
          stem: "How many fingers? (Teacher shows 3 fingers)",
          options: [
            { key: "A", text: "Two" },
            { key: "B", text: "Three" },
            { key: "C", text: "Four" },
            { key: "D", text: "Five" },
          ],
          correctOption: "B",
          markingScheme: "1 mark for B. Accept 'three' in any accent.",
        },
        {
          id: "BL-12",
          section: "Number Words (Cross-check)",
          flnStrand: "VOC",
          lessonIds: [],
          competency: "Recognise number word ONE",
          bloomsLevel: "Remember",
          format: "mcq",
          marks: 1,
          deliveryMode: "oral-group",
          stem: "Which word is ONE?",
          stimulusNote: "Show words: one, two, three, four (mixed fonts).",
          options: [
            { key: "A", text: "one" },
            { key: "B", text: "two" },
            { key: "C", text: "three" },
            { key: "D", text: "four" },
          ],
          correctOption: "A",
          markingScheme: "1 mark for A.",
        },
      ],
    },
  ],
};
