import type { AssessmentTool } from "../../types";

export const grade1L2Endline: AssessmentTool = {
  id: "g1-l2-endline",
  type: "endline",
  grade: 1,
  subject: "english",
  bookTrack: "l2",
  title: "Grade 1 English — Endline (End of Year)",
  description:
    "Year-end competency check aligned to all 4 units of My English Book and FLN goals.",
  totalMarks: 29,
  recommendedMinutes: 45,
  version: "2025-26.1",
  administrationNotes: [
    "Mix oral-group (MCQ) and brief written section (last 8 items) if students can write.",
    "If class cannot write yet, administer written items orally with picture options.",
    "Endline uses same tally method as unit tests — aggregated class counts per item.",
    "Compare strand scores with baseline to show growth in the report.",
  ],
  sections: [
    {
      id: "ol-voc",
      title: "Oral Language & Vocabulary",
      flnStrand: "OL",
      items: [
        {
          id: "EL-01",
          section: "Oral Language & Vocabulary",
          flnStrand: "OL",
          lessonIds: ["1.2", "1.5"],
          competency: "Introduce self; use greetings",
          bloomsLevel: "Apply",
          format: "subjective",
          marks: 2,
          deliveryMode: "oral-individual",
          stem: "Say: My name is ___. I am fine, thank you.",
          markingScheme: "2 marks: both sentences clear. 1 mark: only name OR only greeting response. 0: cannot respond.",
          correctResponse: "Full self-intro + fine thank you",
        },
        {
          id: "EL-02",
          section: "Oral Language & Vocabulary",
          flnStrand: "VOC",
          lessonIds: ["1.7", "2.6"],
          competency: "Use can/can't for ability",
          bloomsLevel: "Apply",
          format: "mcq",
          marks: 1,
          deliveryMode: "oral-group",
          stem: "Birds can ___.",
          options: [
            { key: "A", text: "fly" },
            { key: "B", text: "swim only" },
            { key: "C", text: "drive" },
            { key: "D", text: "cook" },
          ],
          correctOption: "A",
          markingScheme: "1 mark for A.",
        },
        {
          id: "EL-03",
          section: "Oral Language & Vocabulary",
          flnStrand: "VOC",
          lessonIds: ["4.7"],
          competency: "Name community helpers",
          bloomsLevel: "Remember",
          format: "mcq",
          marks: 1,
          deliveryMode: "oral-group",
          stem: "Who treats sick people?",
          options: [
            { key: "A", text: "Doctor" },
            { key: "B", text: "Farmer" },
            { key: "C", text: "Driver" },
            { key: "D", text: "Tailor" },
          ],
          correctOption: "A",
          markingScheme: "1 mark for A.",
        },
        {
          id: "EL-04",
          section: "Oral Language & Vocabulary",
          flnStrand: "VOC",
          lessonIds: ["3.1"],
          competency: "Name colours; traffic signals",
          bloomsLevel: "Understand",
          format: "mcq",
          marks: 1,
          deliveryMode: "oral-group",
          stem: "Red light means ___.",
          options: [
            { key: "A", text: "Stop" },
            { key: "B", text: "Go" },
            { key: "C", text: "Run" },
            { key: "D", text: "Sleep" },
          ],
          correctOption: "A",
          markingScheme: "1 mark for A.",
        },
      ],
    },
    {
      id: "dec",
      title: "Phonics & Decoding",
      flnStrand: "DEC",
      items: [
        {
          id: "EL-05",
          section: "Phonics & Decoding",
          flnStrand: "DEC",
          lessonIds: ["1.6", "3.4"],
          competency: "Letter-sound correspondence",
          bloomsLevel: "Remember",
          format: "mcq",
          marks: 1,
          deliveryMode: "oral-group",
          stem: "Which letter makes /m/ sound?",
          options: [
            { key: "A", text: "m" },
            { key: "B", text: "n" },
            { key: "C", text: "w" },
            { key: "D", text: "v" },
          ],
          correctOption: "A",
          markingScheme: "1 mark for A.",
        },
        {
          id: "EL-06",
          section: "Phonics & Decoding",
          flnStrand: "DEC",
          lessonIds: ["1.6", "2.5"],
          competency: "Read CVC words",
          bloomsLevel: "Apply",
          format: "mcq",
          marks: 1,
          deliveryMode: "oral-group",
          stem: "Read: c-a-t. Which word is it?",
          options: [
            { key: "A", text: "cat" },
            { key: "B", text: "cap" },
            { key: "C", text: "cot" },
            { key: "D", text: "cut" },
          ],
          correctOption: "A",
          markingScheme: "1 mark for A.",
        },
        {
          id: "EL-07",
          section: "Phonics & Decoding",
          flnStrand: "DEC",
          lessonIds: ["3.5", "3.6"],
          competency: "Match capital to small letter",
          bloomsLevel: "Understand",
          format: "mcq",
          marks: 1,
          deliveryMode: "oral-group",
          stem: "Small letter for B is —",
          options: [
            { key: "A", text: "b" },
            { key: "B", text: "d" },
            { key: "C", text: "p" },
            { key: "D", text: "q" },
          ],
          correctOption: "A",
          markingScheme: "1 mark for A.",
        },
        {
          id: "EL-08",
          section: "Phonics & Decoding",
          flnStrand: "PA",
          lessonIds: ["1.10", "3.8"],
          competency: "Identify rhyming / word family",
          bloomsLevel: "Understand",
          format: "mcq",
          marks: 1,
          deliveryMode: "oral-group",
          stem: "Which word rhymes with HAT?",
          options: [
            { key: "A", text: "mat" },
            { key: "B", text: "hen" },
            { key: "C", text: "sun" },
            { key: "D", text: "dog" },
          ],
          correctOption: "A",
          markingScheme: "1 mark for A.",
        },
      ],
    },
    {
      id: "rc",
      title: "Reading Comprehension",
      flnStrand: "RC",
      items: [
        {
          id: "EL-09",
          section: "Reading Comprehension",
          flnStrand: "RC",
          lessonIds: ["1.11"],
          competency: "Story comprehension — who/why",
          bloomsLevel: "Understand",
          format: "mcq",
          marks: 2,
          deliveryMode: "oral-group",
          stem: "In 'We want rain', who wants rain to dance?",
          stimulusNote: "Teacher reads 2-sentence summary if story not recently taught.",
          options: [
            { key: "A", text: "Peacock" },
            { key: "B", text: "Teacher" },
            { key: "C", text: "Doctor" },
            { key: "D", text: "Driver" },
          ],
          correctOption: "A",
          markingScheme: "2 marks for A.",
        },
        {
          id: "EL-10",
          section: "Reading Comprehension",
          flnStrand: "RC",
          lessonIds: ["2.10", "3.10"],
          competency: "Story moral / sequencing",
          bloomsLevel: "Understand",
          format: "mcq",
          marks: 2,
          deliveryMode: "oral-group",
          stem: "In 'The Ant and the Pigeon', who helped whom?",
          options: [
            { key: "A", text: "Pigeon saved ant; ant saved pigeon later" },
            { key: "B", text: "Ant ate pigeon" },
            { key: "C", text: "Hunter helped ant" },
            { key: "D", text: "Nobody helped" },
          ],
          correctOption: "A",
          markingScheme: "2 marks for A. 1 mark if only one direction of help mentioned orally.",
        },
        {
          id: "EL-11",
          section: "Reading Comprehension",
          flnStrand: "RC",
          lessonIds: ["4.4", "4.5"],
          competency: "Prepositions; possessives",
          bloomsLevel: "Apply",
          format: "mcq",
          marks: 1,
          deliveryMode: "oral-group",
          stem: "The book is ___ the table. (on / under)",
          options: [
            { key: "A", text: "on" },
            { key: "B", text: "under" },
            { key: "C", text: "in the sky" },
            { key: "D", text: "behind teacher" },
          ],
          correctOption: "A",
          markingScheme: "1 mark for A (show picture: book on table).",
        },
      ],
    },
    {
      id: "rf-wr",
      title: "Reading & Writing",
      flnStrand: "RF",
      items: [
        {
          id: "EL-12",
          section: "Reading & Writing",
          flnStrand: "RF",
          lessonIds: ["3.5"],
          competency: "Read sight words",
          bloomsLevel: "Apply",
          format: "subjective",
          marks: 2,
          deliveryMode: "oral-individual",
          stem: "Read aloud: the, and, is (flashcard strip)",
          markingScheme: "2 marks: 3/3 correct. 1 mark: 2/3. 0: 0–1 correct.",
          correctResponse: "Reads the, and, is",
        },
        {
          id: "EL-13",
          section: "Reading & Writing",
          flnStrand: "WR",
          lessonIds: ["3.6"],
          competency: "Write small letters",
          bloomsLevel: "Apply",
          format: "subjective",
          marks: 2,
          deliveryMode: "performance",
          stem: "Write small letters: a, m, t (on slate/paper)",
          markingScheme: "2 marks: 3/3 recognisable. 1 mark: 2/3. 0: 0–1.",
          correctResponse: "Writes a, m, t",
        },
      ],
    },
    {
      id: "time-num",
      title: "Time, Numbers & Calendar",
      flnStrand: "VOC",
      items: [
        {
          id: "EL-14",
          section: "Time, Numbers & Calendar",
          flnStrand: "VOC",
          lessonIds: ["3.7"],
          competency: "Days of the week",
          bloomsLevel: "Remember",
          format: "mcq",
          marks: 1,
          deliveryMode: "oral-group",
          stem: "Which day comes after Monday?",
          options: [
            { key: "A", text: "Tuesday" },
            { key: "B", text: "Sunday" },
            { key: "C", text: "Friday" },
            { key: "D", text: "Wednesday" },
          ],
          correctOption: "A",
          markingScheme: "1 mark for A.",
        },
        {
          id: "EL-15",
          section: "Time, Numbers & Calendar",
          flnStrand: "VOC",
          lessonIds: ["3.9"],
          competency: "Numbers 0–10",
          bloomsLevel: "Apply",
          format: "mcq",
          marks: 1,
          deliveryMode: "oral-group",
          stem: "How many? (Show 7 objects)",
          options: [
            { key: "A", text: "Five" },
            { key: "B", text: "Six" },
            { key: "C", text: "Seven" },
            { key: "D", text: "Eight" },
          ],
          correctOption: "C",
          markingScheme: "1 mark for C.",
        },
        {
          id: "EL-16",
          section: "Time, Numbers & Calendar",
          flnStrand: "VOC",
          lessonIds: ["4.1"],
          competency: "Months of the year",
          bloomsLevel: "Remember",
          format: "mcq",
          marks: 1,
          deliveryMode: "oral-group",
          stem: "The year starts with ___.",
          options: [
            { key: "A", text: "January" },
            { key: "B", text: "March" },
            { key: "C", text: "December" },
            { key: "D", text: "July" },
          ],
          correctOption: "A",
          markingScheme: "1 mark for A.",
        },
      ],
    },
    {
      id: "integrate",
      title: "Integrated Application",
      flnStrand: "OL",
      items: [
        {
          id: "EL-17",
          section: "Integrated Application",
          flnStrand: "OL",
          lessonIds: ["4.2"],
          competency: "Festival greetings",
          bloomsLevel: "Apply",
          format: "subjective",
          marks: 2,
          deliveryMode: "oral-individual",
          stem: "What do you say on Diwali?",
          markingScheme: "2 marks: Happy Diwali (or equivalent). 1 mark: partial attempt. 0: no response.",
          correctResponse: "Happy Diwali",
        },
        {
          id: "EL-18",
          section: "Integrated Application",
          flnStrand: "VOC",
          lessonIds: ["2.1", "2.3"],
          competency: "Express preference",
          bloomsLevel: "Apply",
          format: "subjective",
          marks: 2,
          deliveryMode: "oral-individual",
          stem: "Say: I like ___. (vegetable or playground object)",
          markingScheme: "2 marks: complete sentence with English word. 1 mark: word only. 0: no English.",
          correctResponse: "I like carrots / I like slide",
        },
        {
          id: "EL-19",
          section: "Integrated Application",
          flnStrand: "OL",
          lessonIds: ["2.9", "3.3"],
          competency: "Follow 3-step instructions",
          bloomsLevel: "Apply",
          format: "subjective",
          marks: 2,
          deliveryMode: "performance",
          stem: "Stand up. Pick up pencil. Show me.",
          markingScheme: "2 marks: all 3 steps. 1 mark: 2 steps. 0: 0–1 step.",
          correctResponse: "Completes 3 steps in order",
        },
        {
          id: "EL-20",
          section: "Integrated Application",
          flnStrand: "RC",
          lessonIds: ["4.8", "4.9"],
          competency: "Gratitude / adjectives",
          bloomsLevel: "Apply",
          format: "subjective",
          marks: 2,
          deliveryMode: "oral-individual",
          stem: "Say: Thank you for ___.",
          markingScheme: "2 marks: thank you + noun (food/birds/family). 1 mark: Thank you only. 0: no response.",
          correctResponse: "Thank you for food / birds / everything",
        },
      ],
    },
  ],
};
