import type { AssessmentTool, AssessmentItem } from "../../types";

function unitTool(
  groupId: string,
  groupName: string,
  lessonIds: string[],
  focus: string,
  items: AssessmentItem[],
): AssessmentTool {
  const totalMarks = items.reduce((s, i) => s + i.marks, 0);
  return {
    id: `g1-l2-unit-${groupId}`,
    type: "unit",
    grade: 1,
    subject: "english",
    bookTrack: "l2",
    groupId,
    groupName,
    lessonIds,
    focus,
    title: `Unit Test — ${groupName}`,
    description: focus,
    totalMarks,
    recommendedMinutes: 20,
    version: "2025-26.1",
    administrationNotes: [
      "Administer after completing all lessons in this group.",
      "Use oral-group MCQ for most items; performance items for speaking/actions.",
      "Tally A/B/C/D counts on Assessor Copy data sheet.",
    ],
    sections: [
      {
        id: groupId,
        title: groupName,
        flnStrand: items[0]?.flnStrand ?? "VOC",
        items,
      },
    ],
  };
}

export const grade1L2UnitTests: AssessmentTool[] = [
  unitTool("A1", "Self & Home", ["1.1", "1.2", "1.3"], "Body parts, self-introduction, household objects", [
    { id: "A1-01", section: "Self & Home", flnStrand: "VOC", lessonIds: ["1.1"], competency: "Name body parts", bloomsLevel: "Remember", format: "mcq", marks: 1, deliveryMode: "oral-group", stem: "Touch your ___ — which word? EARS / TABLE", options: [{ key: "A", text: "ears" }, { key: "B", text: "table" }, { key: "C", text: "door" }, { key: "D", text: "fan" }], correctOption: "A", markingScheme: "1 mark for A." },
    { id: "A1-02", section: "Self & Home", flnStrand: "OL", lessonIds: ["1.1"], competency: "Follow instruction: touch body part", bloomsLevel: "Apply", format: "subjective", marks: 2, deliveryMode: "performance", stem: "Touch your shoulders.", markingScheme: "2 marks: correct. 0: wrong/no response.", correctResponse: "Touches shoulders" },
    { id: "A1-03", section: "Self & Home", flnStrand: "OL", lessonIds: ["1.2"], competency: "Introduce self", bloomsLevel: "Apply", format: "subjective", marks: 2, deliveryMode: "oral-individual", stem: "Say: My name is ___.", markingScheme: "2 marks: full sentence. 1 mark: name only. 0: no English.", correctResponse: "My name is [name]" },
    { id: "A1-04", section: "Self & Home", flnStrand: "OL", lessonIds: ["1.2"], competency: "Respond to How are you?", bloomsLevel: "Apply", format: "mcq", marks: 1, deliveryMode: "oral-group", stem: "How are you? Best answer:", options: [{ key: "A", text: "I am fine, thank you" }, { key: "B", text: "I am table" }, { key: "C", text: "Good night" }, { key: "D", text: "Red light" }], correctOption: "A", markingScheme: "1 mark for A." },
    { id: "A1-05", section: "Self & Home", flnStrand: "VOC", lessonIds: ["1.3"], competency: "Name household objects", bloomsLevel: "Remember", format: "mcq", marks: 1, deliveryMode: "oral-group", stem: "This is a ___. (picture: door)", options: [{ key: "A", text: "door" }, { key: "B", text: "nose" }, { key: "C", text: "jump" }, { key: "D", text: "rain" }], correctOption: "A", markingScheme: "1 mark for A." },
    { id: "A1-06", section: "Self & Home", flnStrand: "VOC", lessonIds: ["1.3"], competency: "Where is the ___?", bloomsLevel: "Understand", format: "mcq", marks: 1, deliveryMode: "oral-group", stem: "Where is the clock? (picture: clock on wall)", options: [{ key: "A", text: "On the wall" }, { key: "B", text: "Under the bed" }, { key: "C", text: "In the sky" }, { key: "D", text: "On my nose" }], correctOption: "A", markingScheme: "1 mark for A." },
    { id: "A1-07", section: "Self & Home", flnStrand: "OL", lessonIds: ["1.1", "1.3"], competency: "This is my ___", bloomsLevel: "Apply", format: "subjective", marks: 2, deliveryMode: "oral-individual", stem: "Say: This is my hand.", markingScheme: "2 marks: clear sentence. 1 mark: hand only. 0: no response.", correctResponse: "This is my hand" },
    { id: "A1-08", section: "Self & Home", flnStrand: "RC", lessonIds: ["1.3"], competency: "Picture talk — home", bloomsLevel: "Understand", format: "mcq", marks: 1, deliveryMode: "oral-group", stem: "We sit on a ___.", options: [{ key: "A", text: "sofa" }, { key: "B", text: "rain" }, { key: "C", text: "Monday" }, { key: "D", text: "fly" }], correctOption: "A", markingScheme: "1 mark for A." },
  ]),

  unitTool("A2", "Actions & Routines", ["1.4", "1.5", "1.7"], "Action words, daily routine, greetings, can/can't", [
    { id: "A2-01", section: "Actions & Routines", flnStrand: "VOC", lessonIds: ["1.4"], competency: "Action words", bloomsLevel: "Remember", format: "mcq", marks: 1, deliveryMode: "oral-group", stem: "Clap your ___", options: [{ key: "A", text: "hands" }, { key: "B", text: "months" }, { key: "C", text: "doctor" }, { key: "D", text: "January" }], correctOption: "A", markingScheme: "1 mark for A." },
    { id: "A2-02", section: "Actions & Routines", flnStrand: "OL", lessonIds: ["1.4"], competency: "Follow multi-step instructions", bloomsLevel: "Apply", format: "subjective", marks: 2, deliveryMode: "performance", stem: "Stand up. Sit down.", markingScheme: "2 marks: both actions. 1 mark: one. 0: neither.", correctResponse: "Stand then sit" },
    { id: "A2-03", section: "Actions & Routines", flnStrand: "VOC", lessonIds: ["1.5"], competency: "Greetings by time of day", bloomsLevel: "Understand", format: "mcq", marks: 1, deliveryMode: "oral-group", stem: "At morning assembly we say:", options: [{ key: "A", text: "Good morning" }, { key: "B", text: "Good night" }, { key: "C", text: "Happy Birthday" }, { key: "D", text: "Thank you God" }], correctOption: "A", markingScheme: "1 mark for A." },
    { id: "A2-04", section: "Actions & Routines", flnStrand: "VOC", lessonIds: ["1.5"], competency: "Daily routine words", bloomsLevel: "Remember", format: "mcq", marks: 1, deliveryMode: "oral-group", stem: "We eat ___ in the morning.", options: [{ key: "A", text: "breakfast" }, { key: "B", text: "homework" }, { key: "C", text: "uniform" }, { key: "D", text: "traffic" }], correctOption: "A", markingScheme: "1 mark for A." },
    { id: "A2-05", section: "Actions & Routines", flnStrand: "OL", lessonIds: ["1.7"], competency: "Can you ___?", bloomsLevel: "Apply", format: "mcq", marks: 1, deliveryMode: "oral-group", stem: "Can you jump? Yes, I ___.", options: [{ key: "A", text: "can" }, { key: "B", text: "can't" }, { key: "C", text: "am" }, { key: "D", text: "is" }], correctOption: "A", markingScheme: "1 mark for A." },
    { id: "A2-06", section: "Actions & Routines", flnStrand: "OL", lessonIds: ["1.7"], competency: "Can't — impossible action", bloomsLevel: "Understand", format: "mcq", marks: 1, deliveryMode: "oral-group", stem: "Can you fly? No, I ___.", options: [{ key: "A", text: "can't" }, { key: "B", text: "can" }, { key: "C", text: "do" }, { key: "D", text: "like" }], correctOption: "A", markingScheme: "1 mark for A." },
    { id: "A2-07", section: "Actions & Routines", flnStrand: "OL", lessonIds: ["1.4", "1.7"], competency: "Give instruction to classmate", bloomsLevel: "Apply", format: "subjective", marks: 2, deliveryMode: "oral-individual", stem: "Tell friend: Stand up.", markingScheme: "2 marks: clear instruction. 1 mark: attempt. 0: no English.", correctResponse: "Stand up" },
    { id: "A2-08", section: "Actions & Routines", flnStrand: "VOC", lessonIds: ["1.5"], competency: "Sequence morning routine", bloomsLevel: "Understand", format: "mcq", marks: 1, deliveryMode: "oral-group", stem: "First we wake up, then we ___ teeth.", options: [{ key: "A", text: "brush" }, { key: "B", text: "sleep" }, { key: "C", text: "drive" }, { key: "D", text: "cook" }], correctOption: "A", markingScheme: "1 mark for A." },
  ]),

  unitTool("A3", "Phonics 1 & Classroom", ["1.6", "1.8", "1.9"], "Letters b-c-p-t-a-d-f-m-n-e, CVC words, classroom objects", [
    { id: "A3-01", section: "Phonics 1", flnStrand: "DEC", lessonIds: ["1.6"], competency: "Initial sound /b/", bloomsLevel: "Remember", format: "mcq", marks: 1, deliveryMode: "oral-group", stem: "Which starts with /b/?", options: [{ key: "A", text: "bat" }, { key: "B", text: "cat" }, { key: "C", text: "pen" }, { key: "D", text: "top" }], correctOption: "A", markingScheme: "1 mark for A." },
    { id: "A3-02", section: "Phonics 1", flnStrand: "DEC", lessonIds: ["1.6"], competency: "Read CVC word", bloomsLevel: "Apply", format: "mcq", marks: 1, deliveryMode: "oral-group", stem: "c-a-t = ?", options: [{ key: "A", text: "cat" }, { key: "B", text: "cap" }, { key: "C", text: "cot" }, { key: "D", text: "cut" }], correctOption: "A", markingScheme: "1 mark for A." },
    { id: "A3-03", section: "Phonics 1", flnStrand: "VOC", lessonIds: ["1.8"], competency: "Classroom objects", bloomsLevel: "Remember", format: "mcq", marks: 1, deliveryMode: "oral-group", stem: "We write on the ___.", options: [{ key: "A", text: "blackboard" }, { key: "B", text: "rain" }, { key: "C", text: "peacock" }, { key: "D", text: "Tuesday" }], correctOption: "A", markingScheme: "1 mark for A." },
    { id: "A3-04", section: "Phonics 1", flnStrand: "VOC", lessonIds: ["1.8"], competency: "Where is the ___?", bloomsLevel: "Understand", format: "mcq", marks: 1, deliveryMode: "oral-group", stem: "Show me the duster.", stimulusNote: "Point to duster in classroom picture.", options: [{ key: "A", text: "Points to duster" }, { key: "B", text: "Points to bench" }, { key: "C", text: "Points to door" }, { key: "D", text: "No response" }], correctOption: "A", markingScheme: "1 mark for A." },
    { id: "A3-05", section: "Phonics 1", flnStrand: "DEC", lessonIds: ["1.9"], competency: "Short e CVC", bloomsLevel: "Apply", format: "mcq", marks: 1, deliveryMode: "oral-group", stem: "p-e-n = ?", options: [{ key: "A", text: "pen" }, { key: "B", text: "pan" }, { key: "C", text: "pin" }, { key: "D", text: "pet" }], correctOption: "A", markingScheme: "1 mark for A." },
    { id: "A3-06", section: "Phonics 1", flnStrand: "DEC", lessonIds: ["1.9"], competency: "Letter-sound /m/", bloomsLevel: "Remember", format: "mcq", marks: 1, deliveryMode: "oral-group", stem: "Which picture is mango?", options: [{ key: "A", text: "Mango" }, { key: "B", text: "Nest" }, { key: "C", text: "Fox" }, { key: "D", text: "Doll" }], correctOption: "A", markingScheme: "1 mark for A." },
    { id: "A3-07", section: "Phonics 1", flnStrand: "WR", lessonIds: ["1.6"], competency: "Write CVC from dictation", bloomsLevel: "Apply", format: "subjective", marks: 2, deliveryMode: "performance", stem: "Write: cat (on slate)", markingScheme: "2 marks: correct letters in order. 1 mark: 2/3 letters. 0: wrong.", correctResponse: "cat" },
    { id: "A3-08", section: "Phonics 1", flnStrand: "OL", lessonIds: ["1.8"], competency: "This is a ___ (classroom)", bloomsLevel: "Apply", format: "subjective", marks: 2, deliveryMode: "oral-individual", stem: "Say: This is a book.", markingScheme: "2 marks: full sentence. 1 mark: book only.", correctResponse: "This is a book" },
  ]),

  unitTool("A4", "Nature & Stories 1", ["1.10", "1.11"], "Rain poem, seasons, first story comprehension", [
    { id: "A4-01", section: "Nature & Stories 1", flnStrand: "VOC", lessonIds: ["1.10"], competency: "Rain vocabulary", bloomsLevel: "Remember", format: "mcq", marks: 1, deliveryMode: "oral-group", stem: "Rain falls from the ___.", options: [{ key: "A", text: "sky" }, { key: "B", text: "table" }, { key: "C", text: "book" }, { key: "D", text: "chair" }], correctOption: "A", markingScheme: "1 mark for A." },
    { id: "A4-02", section: "Nature & Stories 1", flnStrand: "PA", lessonIds: ["1.10"], competency: "Rhyming words", bloomsLevel: "Understand", format: "mcq", marks: 1, deliveryMode: "oral-group", stem: "Tip-tap rhymes with ___", options: [{ key: "A", text: "clap" }, { key: "B", text: "rain/sky pair from poem" }, { key: "C", text: "dog" }, { key: "D", text: "January" }], correctOption: "B", markingScheme: "1 mark for rain/splash sound pair — accept joy/toy if discussed in class." },
    { id: "A4-03", section: "Nature & Stories 1", flnStrand: "RC", lessonIds: ["1.11"], competency: "Story characters", bloomsLevel: "Remember", format: "mcq", marks: 1, deliveryMode: "oral-group", stem: "Who wants rain to dance?", options: [{ key: "A", text: "Peacock" }, { key: "B", text: "Teacher" }, { key: "C", text: "Clock" }, { key: "D", text: "Duster" }], correctOption: "A", markingScheme: "1 mark for A." },
    { id: "A4-04", section: "Nature & Stories 1", flnStrand: "RC", lessonIds: ["1.11"], competency: "Why character wants rain", bloomsLevel: "Understand", format: "mcq", marks: 1, deliveryMode: "oral-group", stem: "Farmer wants rain for ___.", options: [{ key: "A", text: "seeds/crops" }, { key: "B", text: "homework" }, { key: "C", text: "birthday party" }, { key: "D", text: "traffic" }], correctOption: "A", markingScheme: "1 mark for A." },
    { id: "A4-05", section: "Nature & Stories 1", flnStrand: "RC", lessonIds: ["1.11"], competency: "Sequence story events", bloomsLevel: "Understand", format: "mcq", marks: 2, deliveryMode: "oral-group", stem: "First ___, then rain comes.", options: [{ key: "A", text: "clouds come" }, { key: "B", text: "school closes forever" }, { key: "C", text: "we eat breakfast" }, { key: "D", text: "write letters" }], correctOption: "A", markingScheme: "2 marks for A." },
    { id: "A4-06", section: "Nature & Stories 1", flnStrand: "OL", lessonIds: ["1.10"], competency: "Recite poem line", bloomsLevel: "Apply", format: "subjective", marks: 2, deliveryMode: "oral-individual", stem: "Say one line from Tip-Tap poem.", markingScheme: "2 marks: clear line. 1 mark: partial. 0: no attempt.", correctResponse: "Any line from poem" },
    { id: "A4-07", section: "Nature & Stories 1", flnStrand: "OL", lessonIds: ["1.11"], competency: "Retell story sentence", bloomsLevel: "Apply", format: "subjective", marks: 2, deliveryMode: "oral-individual", stem: "Say: The fish wants rain.", markingScheme: "2 marks: correct idea in English. 1 mark: fish/rain word only.", correctResponse: "Fish wants rain" },
    { id: "A4-08", section: "Nature & Stories 1", flnStrand: "VOC", lessonIds: ["1.11"], competency: "Story vocabulary", bloomsLevel: "Remember", format: "mcq", marks: 1, deliveryMode: "oral-group", stem: "We make ___ boats in rain.", options: [{ key: "A", text: "paper" }, { key: "B", text: "blackboard" }, { key: "C", text: "doctor" }, { key: "D", text: "alphabet" }], correctOption: "A", markingScheme: "1 mark for A." },
  ]),

  unitTool("B1", "Food & Body 2", ["2.1", "2.2", "2.3"], "Vegetables, fingers, park objects, likes/dislikes", [
    { id: "B1-01", section: "Food & Body 2", flnStrand: "VOC", lessonIds: ["2.1"], competency: "Vegetable names", bloomsLevel: "Remember", format: "mcq", marks: 1, deliveryMode: "oral-group", stem: "Which is a carrot?", options: [{ key: "A", text: "Carrot" }, { key: "B", text: "Bus" }, { key: "C", text: "Monday" }, { key: "D", text: "Clap" }], correctOption: "A", markingScheme: "1 mark for A." },
    { id: "B1-02", section: "Food & Body 2", flnStrand: "OL", lessonIds: ["2.1"], competency: "Express likes", bloomsLevel: "Apply", format: "subjective", marks: 2, deliveryMode: "oral-individual", stem: "Say: I like carrots.", markingScheme: "2 marks: full sentence. 1 mark: I like + any food.", correctResponse: "I like [vegetable]" },
    { id: "B1-03", section: "Food & Body 2", flnStrand: "VOC", lessonIds: ["2.2"], competency: "Finger names", bloomsLevel: "Remember", format: "mcq", marks: 1, deliveryMode: "oral-group", stem: "Smallest finger is ___ finger.", options: [{ key: "A", text: "little" }, { key: "B", text: "middle" }, { key: "C", text: "traffic" }, { key: "D", text: "rain" }], correctOption: "A", markingScheme: "1 mark for A." },
    { id: "B1-04", section: "Food & Body 2", flnStrand: "OL", lessonIds: ["2.2"], competency: "Follow finger song instruction", bloomsLevel: "Apply", format: "subjective", marks: 2, deliveryMode: "performance", stem: "Put a finger on your nose.", markingScheme: "2 marks: correct. 0: wrong.", correctResponse: "Touches nose with finger" },
    { id: "B1-05", section: "Food & Body 2", flnStrand: "VOC", lessonIds: ["2.3"], competency: "Park objects", bloomsLevel: "Remember", format: "mcq", marks: 1, deliveryMode: "oral-group", stem: "We play on the ___.", options: [{ key: "A", text: "slide" }, { key: "B", text: "fan" }, { key: "C", text: "egg" }, { key: "D", text: "nest" }], correctOption: "A", markingScheme: "1 mark for A." },
    { id: "B1-06", section: "Food & Body 2", flnStrand: "OL", lessonIds: ["2.3"], competency: "I like to play on ___", bloomsLevel: "Apply", format: "subjective", marks: 2, deliveryMode: "oral-individual", stem: "Say: I like to play on the swing.", markingScheme: "2 marks: complete. 1 mark: partial.", correctResponse: "I like to play on the swing" },
    { id: "B1-07", section: "Food & Body 2", flnStrand: "VOC", lessonIds: ["2.1"], competency: "Do you like ___?", bloomsLevel: "Apply", format: "mcq", marks: 1, deliveryMode: "oral-group", stem: "Do you like potatoes? Yes, I ___.", options: [{ key: "A", text: "do" }, { key: "B", text: "like" }, { key: "C", text: "can't" }, { key: "D", text: "am" }], correctOption: "A", markingScheme: "1 mark for A (Yes, I do)." },
    { id: "B1-08", section: "Food & Body 2", flnStrand: "RC", lessonIds: ["2.3"], competency: "Describe park scene", bloomsLevel: "Understand", format: "mcq", marks: 1, deliveryMode: "oral-group", stem: "Children play in the ___.", options: [{ key: "A", text: "park" }, { key: "B", text: "kitchen" }, { key: "C", text: "hospital" }, { key: "D", text: "letter m" }], correctOption: "A", markingScheme: "1 mark for A." },
  ]),

  unitTool("B2", "Animals & Social", ["2.4", "2.6", "2.7", "2.9"], "Animals, birds, party vocabulary, social conversations", [
    { id: "B2-01", section: "Animals & Social", flnStrand: "VOC", lessonIds: ["2.4"], competency: "Pet vs wild", bloomsLevel: "Understand", format: "mcq", marks: 1, deliveryMode: "oral-group", stem: "A ___ is a wild animal.", options: [{ key: "A", text: "tiger" }, { key: "B", text: "cat" }, { key: "C", text: "dog" }, { key: "D", text: "cow" }], correctOption: "A", markingScheme: "1 mark for A." },
    { id: "B2-02", section: "Animals & Social", flnStrand: "VOC", lessonIds: ["2.4"], competency: "Animal homes", bloomsLevel: "Understand", format: "mcq", marks: 1, deliveryMode: "oral-group", stem: "A lion lives in a ___.", options: [{ key: "A", text: "den" }, { key: "B", text: "school bag" }, { key: "C", text: "cupboard" }, { key: "D", text: "slide" }], correctOption: "A", markingScheme: "1 mark for A." },
    { id: "B2-03", section: "Animals & Social", flnStrand: "VOC", lessonIds: ["2.6"], competency: "Birds can ___", bloomsLevel: "Apply", format: "mcq", marks: 1, deliveryMode: "oral-group", stem: "Birds can ___.", options: [{ key: "A", text: "fly" }, { key: "B", text: "drive" }, { key: "C", text: "cook" }, { key: "D", text: "write essays" }], correctOption: "A", markingScheme: "1 mark for A." },
    { id: "B2-04", section: "Animals & Social", flnStrand: "VOC", lessonIds: ["2.6"], competency: "Bird body parts", bloomsLevel: "Remember", format: "mcq", marks: 1, deliveryMode: "oral-group", stem: "Birds have ___.", options: [{ key: "A", text: "wings" }, { key: "B", text: "wheels" }, { key: "C", text: "windows" }, { key: "D", text: "months" }], correctOption: "A", markingScheme: "1 mark for A." },
    { id: "B2-05", section: "Animals & Social", flnStrand: "OL", lessonIds: ["2.7"], competency: "Party conversation", bloomsLevel: "Apply", format: "subjective", marks: 2, deliveryMode: "oral-individual", stem: "Say: Happy Birthday!", markingScheme: "2 marks: clear greeting. 1 mark: attempt.", correctResponse: "Happy Birthday" },
    { id: "B2-06", section: "Animals & Social", flnStrand: "VOC", lessonIds: ["2.7"], competency: "Party objects", bloomsLevel: "Remember", format: "mcq", marks: 1, deliveryMode: "oral-group", stem: "We blow ___ on birthday.", options: [{ key: "A", text: "balloons" }, { key: "B", text: "blackboards" }, { key: "C", text: "traffic lights" }, { key: "D", text: "months" }], correctOption: "A", markingScheme: "1 mark for A." },
    { id: "B2-07", section: "Animals & Social", flnStrand: "OL", lessonIds: ["2.9"], competency: "Follow water bell instructions", bloomsLevel: "Apply", format: "subjective", marks: 2, deliveryMode: "performance", stem: "Open your water bottle.", markingScheme: "2 marks: performs action. 0: no/wrong.", correctResponse: "Opens bottle" },
    { id: "B2-08", section: "Animals & Social", flnStrand: "OL", lessonIds: ["2.7"], competency: "Can you play with me?", bloomsLevel: "Apply", format: "mcq", marks: 1, deliveryMode: "oral-group", stem: "Can you play with me? Yes, I ___.", options: [{ key: "A", text: "can" }, { key: "B", text: "can't" }, { key: "C", text: "am fine" }, { key: "D", text: "is" }], correctOption: "A", markingScheme: "1 mark for A." },
  ]),

  unitTool("B3", "Phonics 2", ["2.5", "2.8"], "Letters h-l-r-s-i-g-j-k-q-o, CVC words with i and o", [
    { id: "B3-01", section: "Phonics 2", flnStrand: "DEC", lessonIds: ["2.5"], competency: "Short i CVC", bloomsLevel: "Apply", format: "mcq", marks: 1, deliveryMode: "oral-group", stem: "s-i-t = ?", options: [{ key: "A", text: "sit" }, { key: "B", text: "sat" }, { key: "C", text: "set" }, { key: "D", text: "sip" }], correctOption: "A", markingScheme: "1 mark for A." },
    { id: "B3-02", section: "Phonics 2", flnStrand: "DEC", lessonIds: ["2.5"], competency: "-ip word family", bloomsLevel: "Understand", format: "mcq", marks: 1, deliveryMode: "oral-group", stem: "Which rhymes with lip?", options: [{ key: "A", text: "sip" }, { key: "B", text: "log" }, { key: "C", text: "hen" }, { key: "D", text: "bus" }], correctOption: "A", markingScheme: "1 mark for A." },
    { id: "B3-03", section: "Phonics 2", flnStrand: "DEC", lessonIds: ["2.8"], competency: "Short o CVC", bloomsLevel: "Apply", format: "mcq", marks: 1, deliveryMode: "oral-group", stem: "h-o-t = ?", options: [{ key: "A", text: "hot" }, { key: "B", text: "hat" }, { key: "C", text: "hit" }, { key: "D", text: "hen" }], correctOption: "A", markingScheme: "1 mark for A." },
    { id: "B3-04", section: "Phonics 2", flnStrand: "DEC", lessonIds: ["2.8"], competency: "Initial /g/", bloomsLevel: "Remember", format: "mcq", marks: 1, deliveryMode: "oral-group", stem: "Which starts with /g/?", options: [{ key: "A", text: "goat" }, { key: "B", text: "rat" }, { key: "C", text: "sun" }, { key: "D", text: "lip" }], correctOption: "A", markingScheme: "1 mark for A." },
    { id: "B3-05", section: "Phonics 2", flnStrand: "DEC", lessonIds: ["2.8"], competency: "Queen / qu sound", bloomsLevel: "Remember", format: "mcq", marks: 1, deliveryMode: "oral-group", stem: "Which word has qu?", options: [{ key: "A", text: "queen" }, { key: "B", text: "rat" }, { key: "C", text: "mop" }, { key: "D", text: "sit" }], correctOption: "A", markingScheme: "1 mark for A." },
    { id: "B3-06", section: "Phonics 2", flnStrand: "WR", lessonIds: ["2.5"], competency: "Write -it family word", bloomsLevel: "Apply", format: "subjective", marks: 2, deliveryMode: "performance", stem: "Write: sit", markingScheme: "2 marks: correct. 1 mark: 2/3 letters.", correctResponse: "sit" },
    { id: "B3-07", section: "Phonics 2", flnStrand: "DEC", lessonIds: ["2.5"], competency: "Identify middle vowel", bloomsLevel: "Understand", format: "mcq", marks: 1, deliveryMode: "oral-group", stem: "Middle sound in HIT is:", options: [{ key: "A", text: "i" }, { key: "B", text: "o" }, { key: "C", text: "a" }, { key: "D", text: "e" }], correctOption: "A", markingScheme: "1 mark for A." },
    { id: "B3-08", section: "Phonics 2", flnStrand: "PA", lessonIds: ["2.8"], competency: "-og family", bloomsLevel: "Understand", format: "mcq", marks: 1, deliveryMode: "oral-group", stem: "Which is in -og family?", options: [{ key: "A", text: "dog" }, { key: "B", text: "dip" }, { key: "C", text: "met" }, { key: "D", text: "cup" }], correctOption: "A", markingScheme: "1 mark for A." },
  ]),

  unitTool("B4", "Stories 2", ["2.10"], "Story retelling with dialogue, moral understanding", [
    { id: "B4-01", section: "Stories 2", flnStrand: "RC", lessonIds: ["2.10"], competency: "Story characters", bloomsLevel: "Remember", format: "mcq", marks: 1, deliveryMode: "oral-group", stem: "Who ate the butter?", options: [{ key: "A", text: "Cats" }, { key: "B", text: "Doctor" }, { key: "C", text: "Driver" }, { key: "D", text: "Teacher" }], correctOption: "A", markingScheme: "1 mark for A." },
    { id: "B4-02", section: "Stories 2", flnStrand: "RC", lessonIds: ["2.10"], competency: "Story problem", bloomsLevel: "Understand", format: "mcq", marks: 1, deliveryMode: "oral-group", stem: "Cats fought because ___", options: [{ key: "A", text: "parts were not equal" }, { key: "B", text: "it rained" }, { key: "C", text: "school closed" }, { key: "D", text: "they saw traffic" }], correctOption: "A", markingScheme: "1 mark for A." },
    { id: "B4-03", section: "Stories 2", flnStrand: "RC", lessonIds: ["2.10"], competency: "Story moral", bloomsLevel: "Understand", format: "mcq", marks: 2, deliveryMode: "oral-group", stem: "Story teaches us to ___", options: [{ key: "A", text: "share fairly / not fight" }, { key: "B", text: "hide butter" }, { key: "C", text: "skip school" }, { key: "D", text: "drive bus" }], correctOption: "A", markingScheme: "2 marks for A." },
    { id: "B4-04", section: "Stories 2", flnStrand: "OL", lessonIds: ["2.10"], competency: "Dialogue: It's mine", bloomsLevel: "Apply", format: "subjective", marks: 2, deliveryMode: "oral-individual", stem: "Say: It's mine!", markingScheme: "2 marks: clear. 1 mark: mine only.", correctResponse: "It's mine" },
    { id: "B4-05", section: "Stories 2", flnStrand: "OL", lessonIds: ["2.10"], competency: "Retell one event", bloomsLevel: "Apply", format: "subjective", marks: 2, deliveryMode: "oral-individual", stem: "Say what monkey did.", markingScheme: "2 marks: equal parts idea. 1 mark: monkey word only.", correctResponse: "Monkey made equal parts" },
    { id: "B4-06", section: "Stories 2", flnStrand: "VOC", lessonIds: ["2.10"], competency: "Story vocabulary", bloomsLevel: "Remember", format: "mcq", marks: 1, deliveryMode: "oral-group", stem: "Monkey made two ___ parts.", options: [{ key: "A", text: "equal" }, { key: "B", text: "traffic" }, { key: "C", text: "rainy" }, { key: "D", text: "alphabet" }], correctOption: "A", markingScheme: "1 mark for A." },
    { id: "B4-07", section: "Stories 2", flnStrand: "RC", lessonIds: ["2.10"], competency: "Sequence", bloomsLevel: "Understand", format: "mcq", marks: 1, deliveryMode: "oral-group", stem: "First cats ___, then monkey helped.", options: [{ key: "A", text: "fought" }, { key: "B", text: "slept" }, { key: "C", text: "drove" }, { key: "D", text: "counted months" }], correctOption: "A", markingScheme: "1 mark for A." },
    { id: "B4-08", section: "Stories 2", flnStrand: "OL", lessonIds: ["2.10"], competency: "Don't fight", bloomsLevel: "Apply", format: "subjective", marks: 2, deliveryMode: "oral-individual", stem: "Say: Don't fight.", markingScheme: "2 marks: clear phrase. 1 mark: attempt.", correctResponse: "Don't fight" },
  ]),

  unitTool("C1", "World Around Us", ["3.1", "3.2", "3.3"], "Colours, traffic rules, vehicles, lunch-time instructions", [
    { id: "C1-01", section: "World Around Us", flnStrand: "VOC", lessonIds: ["3.1"], competency: "Traffic signal colours", bloomsLevel: "Remember", format: "mcq", marks: 1, deliveryMode: "oral-group", stem: "Green light means ___.", options: [{ key: "A", text: "Go" }, { key: "B", text: "Stop" }, { key: "C", text: "Sleep" }, { key: "D", text: "Eat" }], correctOption: "A", markingScheme: "1 mark for A." },
    { id: "C1-02", section: "World Around Us", flnStrand: "VOC", lessonIds: ["3.1"], competency: "Colour names", bloomsLevel: "Remember", format: "mcq", marks: 1, deliveryMode: "oral-group", stem: "Sky is usually ___.", options: [{ key: "A", text: "blue" }, { key: "B", text: "brinjal" }, { key: "C", text: "hot" }, { key: "D", text: "sit" }], correctOption: "A", markingScheme: "1 mark for A." },
    { id: "C1-03", section: "World Around Us", flnStrand: "VOC", lessonIds: ["3.2"], competency: "Vehicle names", bloomsLevel: "Remember", format: "mcq", marks: 1, deliveryMode: "oral-group", stem: "We go by ___ on road.", options: [{ key: "A", text: "bus" }, { key: "B", text: "ship only" }, { key: "C", text: "cloud" }, { key: "D", text: "finger" }], correctOption: "A", markingScheme: "1 mark for A." },
    { id: "C1-04", section: "World Around Us", flnStrand: "OL", lessonIds: ["3.2"], competency: "Happy journey", bloomsLevel: "Apply", format: "subjective", marks: 2, deliveryMode: "oral-individual", stem: "Say: Happy journey!", markingScheme: "2 marks: clear. 1 mark: partial.", correctResponse: "Happy journey" },
    { id: "C1-05", section: "World Around Us", flnStrand: "VOC", lessonIds: ["3.2"], competency: "Land/water/air vehicles", bloomsLevel: "Understand", format: "mcq", marks: 1, deliveryMode: "oral-group", stem: "Aeroplane goes in the ___.", options: [{ key: "A", text: "sky" }, { key: "B", text: "plate" }, { key: "C", text: "notebook" }, { key: "D", text: "queue" }], correctOption: "A", markingScheme: "1 mark for A." },
    { id: "C1-06", section: "World Around Us", flnStrand: "OL", lessonIds: ["3.3"], competency: "Lunch instructions", bloomsLevel: "Apply", format: "subjective", marks: 2, deliveryMode: "performance", stem: "Make a queue.", markingScheme: "2 marks: forms line. 0: no.", correctResponse: "Stands in queue" },
    { id: "C1-07", section: "World Around Us", flnStrand: "VOC", lessonIds: ["3.3"], competency: "Don't waste food", bloomsLevel: "Understand", format: "mcq", marks: 1, deliveryMode: "oral-group", stem: "At lunch we should ___", options: [{ key: "A", text: "not waste food" }, { key: "B", text: "throw plate" }, { key: "C", text: "run" }, { key: "D", text: "sleep" }], correctOption: "A", markingScheme: "1 mark for A." },
    { id: "C1-08", section: "World Around Us", flnStrand: "OL", lessonIds: ["3.3"], competency: "Wash hands", bloomsLevel: "Apply", format: "subjective", marks: 2, deliveryMode: "performance", stem: "Show washing hands action.", markingScheme: "2 marks: clear action. 0: no.", correctResponse: "Mimes washing hands" },
  ]),

  unitTool("C2", "Phonics 3 & Alphabet", ["3.4", "3.5", "3.6"], "Complete alphabet, all letter sounds, capital and small letters", [
    { id: "C2-01", section: "Phonics 3", flnStrand: "DEC", lessonIds: ["3.4"], competency: "Final letters v-z-u", bloomsLevel: "Remember", format: "mcq", marks: 1, deliveryMode: "oral-group", stem: "Which starts with /z/?", options: [{ key: "A", text: "zebra" }, { key: "B", text: "van" }, { key: "C", text: "well" }, { key: "D", text: "yarn" }], correctOption: "A", markingScheme: "1 mark for A." },
    { id: "C2-02", section: "Phonics 3", flnStrand: "DEC", lessonIds: ["3.4"], competency: "Short u CVC", bloomsLevel: "Apply", format: "mcq", marks: 1, deliveryMode: "oral-group", stem: "s-u-n = ?", options: [{ key: "A", text: "sun" }, { key: "B", text: "sin" }, { key: "C", text: "son" }, { key: "D", text: "san" }], correctOption: "A", markingScheme: "1 mark for A." },
    { id: "C2-03", section: "Phonics 3", flnStrand: "RF", lessonIds: ["3.5"], competency: "Alphabet song / letter order", bloomsLevel: "Remember", format: "mcq", marks: 1, deliveryMode: "oral-group", stem: "Which comes after B?", options: [{ key: "A", text: "C" }, { key: "B", text: "A" }, { key: "C", text: "Z" }, { key: "D", text: "M" }], correctOption: "A", markingScheme: "1 mark for A." },
    { id: "C2-04", section: "Phonics 3", flnStrand: "RF", lessonIds: ["3.5"], competency: "Sight word", bloomsLevel: "Apply", format: "subjective", marks: 2, deliveryMode: "oral-individual", stem: "Read: the", markingScheme: "2 marks: correct. 0: wrong.", correctResponse: "the" },
    { id: "C2-05", section: "Phonics 3", flnStrand: "WR", lessonIds: ["3.6"], competency: "Capital-small match", bloomsLevel: "Understand", format: "mcq", marks: 1, deliveryMode: "oral-group", stem: "Small letter for K is", options: [{ key: "A", text: "k" }, { key: "B", text: "h" }, { key: "C", text: "b" }, { key: "D", text: "p" }], correctOption: "A", markingScheme: "1 mark for A." },
    { id: "C2-06", section: "Phonics 3", flnStrand: "WR", lessonIds: ["3.6"], competency: "Write letters", bloomsLevel: "Apply", format: "subjective", marks: 2, deliveryMode: "performance", stem: "Write: M and m", markingScheme: "2 marks: both recognisable. 1 mark: one correct.", correctResponse: "M and m" },
    { id: "C2-07", section: "Phonics 3", flnStrand: "DEC", lessonIds: ["3.4"], competency: "-un family", bloomsLevel: "Understand", format: "mcq", marks: 1, deliveryMode: "oral-group", stem: "Which rhymes with sun?", options: [{ key: "A", text: "fun" }, { key: "B", text: "cat" }, { key: "C", text: "dog" }, { key: "D", text: "goat" }], correctOption: "A", markingScheme: "1 mark for A." },
    { id: "C2-08", section: "Phonics 3", flnStrand: "DEC", lessonIds: ["3.5"], competency: "All 26 sounds known", bloomsLevel: "Apply", format: "subjective", marks: 2, deliveryMode: "oral-individual", stem: "Say sound of letter S.", markingScheme: "2 marks: /s/ correct. 0: wrong letter sound.", correctResponse: "/s/" },
  ]),

  unitTool("C3", "Time & Numbers", ["3.7", "3.8", "3.9"], "Days of week, word families, numbers 0-10, shapes", [
    { id: "C3-01", section: "Time & Numbers", flnStrand: "VOC", lessonIds: ["3.7"], competency: "Days of week order", bloomsLevel: "Remember", format: "mcq", marks: 1, deliveryMode: "oral-group", stem: "First day of week is ___.", options: [{ key: "A", text: "Monday" }, { key: "B", text: "Friday" }, { key: "C", text: "Sunday only as weekend" }, { key: "D", text: "March" }], correctOption: "A", markingScheme: "1 mark for A (school context)." },
    { id: "C3-02", section: "Time & Numbers", flnStrand: "OL", lessonIds: ["3.7"], competency: "Today is ___", bloomsLevel: "Apply", format: "subjective", marks: 2, deliveryMode: "oral-individual", stem: "Say: Today is [day].", markingScheme: "2 marks: correct day name. 1 mark: attempt.", correctResponse: "Today is Monday" },
    { id: "C3-03", section: "Time & Numbers", flnStrand: "DEC", lessonIds: ["3.8"], competency: "Word families", bloomsLevel: "Understand", format: "mcq", marks: 1, deliveryMode: "oral-group", stem: "Which is in -an family?", options: [{ key: "A", text: "man" }, { key: "B", text: "sit" }, { key: "C", text: "hot" }, { key: "D", text: "bug" }], correctOption: "A", markingScheme: "1 mark for A." },
    { id: "C3-04", section: "Time & Numbers", flnStrand: "DEC", lessonIds: ["3.8"], competency: "Compound words", bloomsLevel: "Understand", format: "mcq", marks: 1, deliveryMode: "oral-group", stem: "Pen + cil = ?", options: [{ key: "A", text: "pencil" }, { key: "B", text: "pencat" }, { key: "C", text: "cilpen" }, { key: "D", text: "pen only" }], correctOption: "A", markingScheme: "1 mark for A." },
    { id: "C3-05", section: "Time & Numbers", flnStrand: "VOC", lessonIds: ["3.9"], competency: "Numbers 0-10", bloomsLevel: "Apply", format: "mcq", marks: 1, deliveryMode: "oral-group", stem: "Show 5 fingers — answer:", options: [{ key: "A", text: "Five" }, { key: "B", text: "Two" }, { key: "C", text: "Ten" }, { key: "D", text: "Zero" }], correctOption: "A", markingScheme: "1 mark for A." },
    { id: "C3-06", section: "Time & Numbers", flnStrand: "VOC", lessonIds: ["3.9"], competency: "Shape names", bloomsLevel: "Remember", format: "mcq", marks: 1, deliveryMode: "oral-group", stem: "A ball shape is a ___.", options: [{ key: "A", text: "circle" }, { key: "B", text: "square" }, { key: "C", text: "triangle" }, { key: "D", text: "Monday" }], correctOption: "A", markingScheme: "1 mark for A." },
    { id: "C3-07", section: "Time & Numbers", flnStrand: "OL", lessonIds: ["3.9"], competency: "How many ___?", bloomsLevel: "Apply", format: "subjective", marks: 2, deliveryMode: "oral-individual", stem: "Answer: How many books? (show 4)", markingScheme: "2 marks: Four/I have four. 1 mark: number only.", correctResponse: "Four books" },
    { id: "C3-08", section: "Time & Numbers", flnStrand: "OL", lessonIds: ["3.9"], competency: "Please give me ___", bloomsLevel: "Apply", format: "subjective", marks: 2, deliveryMode: "oral-individual", stem: "Say: Please give me one pencil.", markingScheme: "2 marks: polite full sentence. 1 mark: partial.", correctResponse: "Please give me one pencil" },
  ]),

  unitTool("C4", "Stories 3", ["3.10"], "Moral story, sequencing, cause and effect", [
    { id: "C4-01", section: "Stories 3", flnStrand: "RC", lessonIds: ["3.10"], competency: "Story characters", bloomsLevel: "Remember", format: "mcq", marks: 1, deliveryMode: "oral-group", stem: "Story is about ant and ___.", options: [{ key: "A", text: "pigeon" }, { key: "B", text: "bus" }, { key: "C", text: "mixer" }, { key: "D", text: "January" }], correctOption: "A", markingScheme: "1 mark for A." },
    { id: "C4-02", section: "Stories 3", flnStrand: "RC", lessonIds: ["3.10"], competency: "Cause and effect", bloomsLevel: "Understand", format: "mcq", marks: 1, deliveryMode: "oral-group", stem: "Ant fell in ___.", options: [{ key: "A", text: "pond" }, { key: "B", text: "school bag" }, { key: "C", text: "traffic light" }, { key: "D", text: "alphabet chart" }], correctOption: "A", markingScheme: "1 mark for A." },
    { id: "C4-03", section: "Stories 3", flnStrand: "RC", lessonIds: ["3.10"], competency: "Help others moral", bloomsLevel: "Understand", format: "mcq", marks: 2, deliveryMode: "oral-group", stem: "Story moral: we should ___.", options: [{ key: "A", text: "help each other" }, { key: "B", text: "fight" }, { key: "C", text: "waste food" }, { key: "D", text: "skip school" }], correctOption: "A", markingScheme: "2 marks for A." },
    { id: "C4-04", section: "Stories 3", flnStrand: "RC", lessonIds: ["3.10"], competency: "Sequence events", bloomsLevel: "Understand", format: "mcq", marks: 1, deliveryMode: "oral-group", stem: "Pigeon saved ant with ___.", options: [{ key: "A", text: "leaf" }, { key: "B", text: "bus" }, { key: "C", text: "duster" }, { key: "D", text: "cake" }], correctOption: "A", markingScheme: "1 mark for A." },
    { id: "C4-05", section: "Stories 3", flnStrand: "OL", lessonIds: ["3.10"], competency: "Retell one event", bloomsLevel: "Apply", format: "subjective", marks: 2, deliveryMode: "oral-individual", stem: "Say: Pigeon helped ant.", markingScheme: "2 marks: clear English. 1 mark: partial.", correctResponse: "Pigeon helped ant" },
    { id: "C4-06", section: "Stories 3", flnStrand: "VOC", lessonIds: ["3.10"], competency: "Story vocabulary", bloomsLevel: "Remember", format: "mcq", marks: 1, deliveryMode: "oral-group", stem: "Hunter had a ___.", options: [{ key: "A", text: "gun" }, { key: "B", text: "pencil" }, { key: "C", text: "slide" }, { key: "D", text: "Tuesday" }], correctOption: "A", markingScheme: "1 mark for A." },
    { id: "C4-07", section: "Stories 3", flnStrand: "RC", lessonIds: ["3.10"], competency: "Ant saved pigeon how", bloomsLevel: "Understand", format: "mcq", marks: 1, deliveryMode: "oral-group", stem: "Ant bit hunter's ___.", options: [{ key: "A", text: "foot" }, { key: "B", text: "book" }, { key: "C", text: "fan" }, { key: "D", text: "month" }], correctOption: "A", markingScheme: "1 mark for A." },
    { id: "C4-08", section: "Stories 3", flnStrand: "OL", lessonIds: ["3.10"], competency: "Dialogue retell", bloomsLevel: "Apply", format: "subjective", marks: 2, deliveryMode: "oral-individual", stem: "Say: Thank you, pigeon.", markingScheme: "2 marks: clear. 1 mark: thank you only.", correctResponse: "Thank you pigeon" },
  ]),

  unitTool("D1", "Calendar & Occasions", ["4.1", "4.2", "4.3"], "Months, festival greetings, hygiene/bath vocabulary", [
    { id: "D1-01", section: "Calendar & Occasions", flnStrand: "VOC", lessonIds: ["4.1"], competency: "Months order", bloomsLevel: "Remember", format: "mcq", marks: 1, deliveryMode: "oral-group", stem: "First month is ___.", options: [{ key: "A", text: "January" }, { key: "B", text: "June" }, { key: "C", text: "December" }, { key: "D", text: "Monday" }], correctOption: "A", markingScheme: "1 mark for A." },
    { id: "D1-02", section: "Calendar & Occasions", flnStrand: "VOC", lessonIds: ["4.1"], competency: "Birthday month", bloomsLevel: "Apply", format: "subjective", marks: 2, deliveryMode: "oral-individual", stem: "Say your birthday month in English.", markingScheme: "2 marks: correct month. 1 mark: attempt.", correctResponse: "My birthday is in [month]" },
    { id: "D1-03", section: "Calendar & Occasions", flnStrand: "OL", lessonIds: ["4.2"], competency: "Festival greetings", bloomsLevel: "Apply", format: "mcq", marks: 1, deliveryMode: "oral-group", stem: "On Diwali we say:", options: [{ key: "A", text: "Happy Diwali" }, { key: "B", text: "Good night" }, { key: "C", text: "Stop" }, { key: "D", text: "Go" }], correctOption: "A", markingScheme: "1 mark for A." },
    { id: "D1-04", section: "Calendar & Occasions", flnStrand: "OL", lessonIds: ["4.2"], competency: "Congratulations", bloomsLevel: "Apply", format: "subjective", marks: 2, deliveryMode: "oral-individual", stem: "Say: Congratulations!", markingScheme: "2 marks: clear. 1 mark: attempt.", correctResponse: "Congratulations" },
    { id: "D1-05", section: "Calendar & Occasions", flnStrand: "VOC", lessonIds: ["4.3"], competency: "Bathroom objects", bloomsLevel: "Remember", format: "mcq", marks: 1, deliveryMode: "oral-group", stem: "We brush teeth with ___.", options: [{ key: "A", text: "toothbrush" }, { key: "B", text: "ladle" }, { key: "C", text: "tractor" }, { key: "D", text: "kite" }], correctOption: "A", markingScheme: "1 mark for A." },
    { id: "D1-06", section: "Calendar & Occasions", flnStrand: "PA", lessonIds: ["4.3"], competency: "Rhyming pairs from poem", bloomsLevel: "Understand", format: "mcq", marks: 1, deliveryMode: "oral-group", stem: "Bath rhymes with ___.", options: [{ key: "A", text: "path/laugh pair from poem" }, { key: "B", text: "cat" }, { key: "C", text: "bus" }, { key: "D", text: "January" }], correctOption: "A", markingScheme: "1 mark for poem rhyme pair." },
    { id: "D1-07", section: "Calendar & Occasions", flnStrand: "OL", lessonIds: ["4.3"], competency: "Recite poem line", bloomsLevel: "Apply", format: "subjective", marks: 2, deliveryMode: "oral-individual", stem: "Say one line from After My Bath.", markingScheme: "2 marks: clear line. 1 mark: partial.", correctResponse: "Any bath poem line" },
    { id: "D1-08", section: "Calendar & Occasions", flnStrand: "VOC", lessonIds: ["4.2"], competency: "Eid greeting", bloomsLevel: "Remember", format: "mcq", marks: 1, deliveryMode: "oral-group", stem: "Eid greeting is:", options: [{ key: "A", text: "Eid Mubarak" }, { key: "B", text: "Happy journey" }, { key: "C", text: "Good morning only" }, { key: "D", text: "Red light" }], correctOption: "A", markingScheme: "1 mark for A." },
  ]),

  unitTool("D2", "Prepositions & Stories 4", ["4.4", "4.5", "4.6"], "On/under/in, possessives mine/yours, emotions, kitchen", [
    { id: "D2-01", section: "Prepositions & Stories 4", flnStrand: "VOC", lessonIds: ["4.4"], competency: "Preposition on", bloomsLevel: "Apply", format: "mcq", marks: 1, deliveryMode: "oral-group", stem: "Book is ___ the table.", options: [{ key: "A", text: "on" }, { key: "B", text: "under" }, { key: "C", text: "fly" }, { key: "D", text: "rain" }], correctOption: "A", markingScheme: "1 mark for A." },
    { id: "D2-02", section: "Prepositions & Stories 4", flnStrand: "VOC", lessonIds: ["4.4"], competency: "Preposition under", bloomsLevel: "Apply", format: "mcq", marks: 1, deliveryMode: "oral-group", stem: "Cat is ___ the chair.", options: [{ key: "A", text: "under" }, { key: "B", text: "on" }, { key: "C", text: "happy" }, { key: "D", text: "mine" }], correctOption: "A", markingScheme: "1 mark for A." },
    { id: "D2-03", section: "Prepositions & Stories 4", flnStrand: "OL", lessonIds: ["4.4"], competency: "Where is my ___?", bloomsLevel: "Apply", format: "subjective", marks: 2, deliveryMode: "oral-individual", stem: "Ask: Where is my bag?", markingScheme: "2 marks: full question. 1 mark: bag/where only.", correctResponse: "Where is my bag?" },
    { id: "D2-04", section: "Prepositions & Stories 4", flnStrand: "RC", lessonIds: ["4.5"], competency: "Possessives mine/yours", bloomsLevel: "Understand", format: "mcq", marks: 1, deliveryMode: "oral-group", stem: "That whistle is ___. (to owner)", options: [{ key: "A", text: "yours" }, { key: "B", text: "mine" }, { key: "C", text: "rain" }, { key: "D", text: "go" }], correctOption: "A", markingScheme: "1 mark for A in context." },
    { id: "D2-05", section: "Prepositions & Stories 4", flnStrand: "VOC", lessonIds: ["4.5"], competency: "Emotions", bloomsLevel: "Remember", format: "mcq", marks: 1, deliveryMode: "oral-group", stem: "When we lose something we feel ___.", options: [{ key: "A", text: "sad" }, { key: "B", text: "traffic" }, { key: "C", text: "Tuesday" }, { key: "D", text: "zebra" }], correctOption: "A", markingScheme: "1 mark for A." },
    { id: "D2-06", section: "Prepositions & Stories 4", flnStrand: "VOC", lessonIds: ["4.6"], competency: "Kitchen objects", bloomsLevel: "Remember", format: "mcq", marks: 1, deliveryMode: "oral-group", stem: "We cook in a ___.", options: [{ key: "A", text: "pan" }, { key: "B", text: "bus" }, { key: "C", text: "wing" }, { key: "D", text: "Monday" }], correctOption: "A", markingScheme: "1 mark for A." },
    { id: "D2-07", section: "Prepositions & Stories 4", flnStrand: "OL", lessonIds: ["4.6"], competency: "Recipe sequence", bloomsLevel: "Apply", format: "subjective", marks: 2, deliveryMode: "oral-individual", stem: "Say: First lemon, then sugar.", markingScheme: "2 marks: sequence words used. 1 mark: partial.", correctResponse: "First/then sequence" },
    { id: "D2-08", section: "Prepositions & Stories 4", flnStrand: "RC", lessonIds: ["4.5"], competency: "Lost and Found retell", bloomsLevel: "Apply", format: "subjective", marks: 2, deliveryMode: "oral-individual", stem: "Say: Is this yours?", markingScheme: "2 marks: clear question. 1 mark: partial.", correctResponse: "Is this yours?" },
  ]),

  unitTool("D3", "Community & Sharing", ["4.7", "4.8", "4.9"], "Community helpers, colours in context, gratitude, adjectives", [
    { id: "D3-01", section: "Community & Sharing", flnStrand: "VOC", lessonIds: ["4.7"], competency: "Community helpers", bloomsLevel: "Remember", format: "mcq", marks: 1, deliveryMode: "oral-group", stem: "A ___ teaches us.", options: [{ key: "A", text: "teacher" }, { key: "B", text: "tiger" }, { key: "C", text: "cloud" }, { key: "D", text: "pencil" }], correctOption: "A", markingScheme: "1 mark for A." },
    { id: "D3-02", section: "Community & Sharing", flnStrand: "OL", lessonIds: ["4.7"], competency: "I am a ___ role-play", bloomsLevel: "Apply", format: "subjective", marks: 2, deliveryMode: "oral-individual", stem: "Say: I am a doctor.", markingScheme: "2 marks: full sentence. 1 mark: doctor only.", correctResponse: "I am a doctor" },
    { id: "D3-03", section: "Community & Sharing", flnStrand: "VOC", lessonIds: ["4.8"], competency: "Sea animals", bloomsLevel: "Remember", format: "mcq", marks: 1, deliveryMode: "oral-group", stem: "A ___ lives in sea.", options: [{ key: "A", text: "dolphin" }, { key: "B", text: "cow" }, { key: "C", text: "goat" }, { key: "D", text: "hen" }], correctOption: "A", markingScheme: "1 mark for A." },
    { id: "D3-04", section: "Community & Sharing", flnStrand: "VOC", lessonIds: ["4.8"], competency: "Adjectives", bloomsLevel: "Understand", format: "mcq", marks: 1, deliveryMode: "oral-group", stem: "Magic fish is ___.", options: [{ key: "A", text: "beautiful" }, { key: "B", text: "under" }, { key: "C", text: "Monday" }, { key: "D", text: "stop" }], correctOption: "A", markingScheme: "1 mark for A." },
    { id: "D3-05", section: "Community & Sharing", flnStrand: "RC", lessonIds: ["4.8"], competency: "Story — sharing colours", bloomsLevel: "Understand", format: "mcq", marks: 1, deliveryMode: "oral-group", stem: "Sea became happy when animals ___.", options: [{ key: "A", text: "shared colours" }, { key: "B", text: "fought" }, { key: "C", text: "skipped school" }, { key: "D", text: " ate butter" }], correctOption: "A", markingScheme: "1 mark for A." },
    { id: "D3-06", section: "Community & Sharing", flnStrand: "OL", lessonIds: ["4.9"], competency: "Thank you God", bloomsLevel: "Apply", format: "subjective", marks: 2, deliveryMode: "oral-individual", stem: "Say: Thank you God for food.", markingScheme: "2 marks: full phrase. 1 mark: thank you only.", correctResponse: "Thank you God for food" },
    { id: "D3-07", section: "Community & Sharing", flnStrand: "VOC", lessonIds: ["4.8"], competency: "Colour words in context", bloomsLevel: "Apply", format: "mcq", marks: 1, deliveryMode: "oral-group", stem: "Sun is ___.", options: [{ key: "A", text: "yellow" }, { key: "B", text: "under" }, { key: "C", text: "mine" }, { key: "D", text: "doctor" }], correctOption: "A", markingScheme: "1 mark for A." },
    { id: "D3-08", section: "Community & Sharing", flnStrand: "OL", lessonIds: ["4.9"], competency: "Gratitude in daily life", bloomsLevel: "Apply", format: "subjective", marks: 2, deliveryMode: "oral-individual", stem: "Say thank you for one thing.", markingScheme: "2 marks: thank you + noun. 1 mark: thank you only.", correctResponse: "Thank you for [gift/help/food]" },
  ]),
];

export function getGrade1L2UnitTest(groupId: string): AssessmentTool | undefined {
  return grade1L2UnitTests.find((t) => t.groupId === groupId);
}
